name: test-prosjekt1/pipeline-test

on:
  push:
  workflow_dispatch:

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true

env:
  DOCKER_USER: brennuvargur
  DOCKER_PASS: DetteErMittPassord

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim-buster
      options: --user root  # Run as root user
    timeout-minutes: 60
    env:
      IMAGE_NAME: brennuvargur/pipeline-test
      IMAGE_TAG: python-app-1.0
    steps:
      - name: Install Git, Git LFS, and dependencies
        run: |
          apt-get update
          apt-get install -y sudo
          sudo apt-get update
          sudo apt-get install -y git
          sudo apt-get install -y curl
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get install -y git-lfs
          sudo git lfs install
          sudo git lfs version  # Check if git-lfs is properly installed
          sudo apt-get install -y make

      - name: Checkout repository with Git LFS support
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 20
          lfs: true

      - name: Run tests
        run: make test  # Ensure the makefile exists with a 'test' target

  build_image:
    needs: run_tests
    runs-on: ubuntu-latest  # Using Ubuntu instead of the Docker CLI image
    timeout-minutes: 60
    env:
      IMAGE_NAME: brennuvargur/pipeline-test
      IMAGE_TAG: python-app-1.0
      DOCKER_TLS_CERTDIR: "/certs"
    steps:
      - name: Install Git, Git LFS, and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get install -y git-lfs
          sudo git lfs install
          sudo git lfs version  # Check if git-lfs is properly installed

      - name: Checkout repository with Git LFS support
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 20
          lfs: true

      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:$IMAGE_TAG
